# Generated by Django 4.2.6 on 2023-10-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.ManyToManyField(to='inventoryRestApi.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=10)),
                ('docType', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('RC', 'RC'), ('NUIP', 'NUIP'), ('CE', 'CE'), ('PS', 'PS'), ('NIP', 'NIP'), ('NES', 'NES')], max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryRestApi.role')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unitsAvailable', models.IntegerField()),
                ('brandId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryRestApi.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryRestApi.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('units', models.PositiveIntegerField()),
                ('movType', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryRestApi.inventoryproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryRestApi.user')),
            ],
        ),
    ]
