# Generated by Django 4.2.6 on 2023-11-17 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
