# Generated by Django 4.2.6 on 2023-11-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryRestApi', '0002_alter_inventorymovement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
